Fix spelling in comments
epics-base/epics-base pull request #197
Opened 2021-08-12 21:03 UTC by mdavidsaver

The charactor of my speling has been impuned!  So with this change I correct in bulk most (although no all) of the spelling errors in C/C++ code comments.  This should be entirely **non-functional**, except for some errSym strings extracted from headers.

I've gone through the diff manually and sorted out a few incorrect changes to code examples in comments.  The raw replacements are [here](https://github.com/epics-base/epics-base/files/6978532/fix.json.txt).

For the curious.  Although only touching 441 lines, this change touches ~20% of the C/C++ code files in Base.

@anjohnson I used an en_US dictionary, so apologies in advance for any words which are now being spelled incorrectly.

2021-08-14 02:07 UTC, anjohnson requested changes
Wow! Have you been having fun with this? I'm pretty sure Jeff still beat you in the total number of mis-spellings though.

I found a few small issues and dictionary holes, see the comments inline. I'm only complaining about the loss of British spelling in a few files where that changes legal wording which I am leery of us doing.

2021-08-14 02:07 UTC, anjohnson commented on modules/database/src/ioc/rsrv/camessage.c
> +     * request for all available elements.  In this case we initialism the
I think you meant `initialize` here.

2021-08-14 02:07 UTC, anjohnson commented on modules/libcom/src/cxxTemplates/resourceLib.h
> +// (if this is inline SUN PRO botches the template instantiate)
The original was correct here, could that word be missing from your dictionary?

2021-08-14 02:07 UTC, anjohnson commented on modules/libcom/src/fdmgr/fdManager.cpp
> +            // an error is re-tuned from select
I think this should be `returned`.

2021-08-14 02:07 UTC, anjohnson commented on modules/libcom/src/flex/ccl.c
> + * acknowledgment:  ``This product includes software developed by the
This is part of the legal license text which must be retained, and I would hesitate to change it; the original spelling is the preferred British form (was UCB's lawyer a Brit?). This comment applies to all copies of this notice in the modules/libcom/src/flex directory which all have the same spelling.

2021-08-14 02:07 UTC, anjohnson commented on modules/libcom/src/flex/dfa.c
> +        /* we sort the accepting set in increasing order so the disambiguate
"disambiguating rule" – a rule for removing ambiguity.
Another originally correct spelling that seems to be missing from your dictionary, the same change also needs to be undone 22 lines below in the same file.

2021-08-14 02:07 UTC, anjohnson commented on modules/libcom/src/flex/tblcmp.c
> + * and an index into the save area where we can find the protos complete
Possessive, belonging to or of the proto. Original is correct.

2021-08-14 02:07 UTC, anjohnson commented on modules/libcom/src/osi/compiler/default/compilerSpecific.h
> +/* The 'inline' key work, possibly with compiler
This change is correct, but I think `key work` should be `keyword`.

2021-08-14 02:07 UTC, anjohnson commented on modules/libcom/src/osi/compiler/gcc/compilerSpecific.h
> + * standards in compliance issues will be fixed by future compiler
**incompliance** (noun) – The condition of being incompliant; a refusal to comply.

Another dictionary hole. You could change the word to non-compliance if that makes the meaning clearer.

2021-08-14 02:07 UTC, anjohnson commented on modules/libcom/src/osi/compiler/msvc/compilerSpecific.h
> + * standards in compliance issues will be fixed by future compiler
See above.

2021-08-14 02:07 UTC, anjohnson commented on modules/libcom/src/osi/os/WIN32/epicsGetopt.c
> + *    must display the following acknowledgment:
Another legal notice from UCB which shouldn't be fixed.

2021-08-14 02:07 UTC, anjohnson commented on modules/libcom/src/osi/os/vxWorks/task_params.h
> +#define CALLBACK_PRI_HIGH 128      /* callback task - generally callback task */
These three should all say `general`.

2021-08-14 02:07 UTC, anjohnson commented on modules/libcom/src/osi/osiSock.h
> + * found and the loopback addresses when subscribing with
Surely there's only one loopback address, so this should be singular.

2021-08-14 19:11 UTC, mdavidsaver commented
> Wow! Have you been having fun with this?

Fun with proofreading?  Not so much.  More like wanting to do this once and be done with it for awhile (like a decade or so).  I did have some fun with regexp to [automate](https://github.com/mdavidsaver/cspell) the process.

> I'm pretty sure Jeff still beat you in the total number of mis-spellings though.

Ah, well.  He didn't have Andrew Johnson looking over his shoulder.

>  found a few small issues and dictionary holes

fyi. I'm checking against the en_US dictionary of HunSpell 2018.04.16-1 (Debian package).

No objections to the un-corrections.  I'll hopefully get to this soon.

2021-08-15 17:23 UTC, mdavidsaver commented
Un-corrections applied.

2021-08-16 15:19 UTC, anjohnson approved these changes
A couple more here, but otherwise this looks good.

2021-08-16 15:19 UTC, anjohnson commented on modules/ca/src/client/tcpiiu.cpp
> +    osiSockIoctl_t bytesPending = 0; /* shut up purifies yapping */
"Purify" was a commercial lint-like tool, so this should be `purify's`

2021-08-16 15:19 UTC, anjohnson commented on modules/libcom/src/misc/shareLib.h
> + * DLL implements must set epicsExportSharedSymbols as above to specify
Let's do `implementers` instead here.

2021-08-29 16:29 UTC, mdavidsaver commented
Applied as e34b6c5c0ce5a112fe79bc34b01401ce64fed9c4

2021-08-29 16:29 UTC, closed without merging