Fix undefined timestamp for NORD field
epics-base/epics-base pull request #359
Opened 2023-03-08 15:49 UTC by henrique-silva

This PR addresses the issues mentioned in #280.

- Adds posting event when NORD is updated only after getting a timestamp.
- Removes posting this same event in the device support layer

Affects aai, aao and waveform records

2023-03-09 15:08 UTC, simon-ess commented
If I understand this correctly, it also affects the sub-array record: https://github.com/epics-base/epics-base/blob/7.0/modules/database/src/std/dev/devSASoft.c#L123

2023-04-24 14:06 UTC, mdavidsaver approved these changes
I think this is acceptable with the addition of a release note entry with a note for any external device support which might be posting `NORD` that this is no longer necessary, and will result in duplicate updates.

2023-04-24 16:19 UTC, anjohnson requested changes
A release note entry will definitely be needed, and should include a description and example of how out-of-tree device support (such as Asyn) should be modified so it still works when compiled against older versions of Base. The best way to handle that is shown below, the first part you'll have to do for each of the record types that you've modified. I'm using the aaiRecord as an example, you can probably copy/paste the code in the second part as your example for the release notes.

Thanks!

----

Add the line
```
%#define AAI_POSTS_NORD
```
to the aaiRecord.dbd.pod file — find where the similar named `HAS_…dset` is defined in the file and add this near to that. The generated aaiRecord.h file will then define that macro.

----

Each device support which already #includes the aaiRecord.h file can use something like this in its `read_aai()` method:
```C
#ifndef AAI_POSTS_NORD
    epicsUInt32 nord = prec->nord;
#endif

…

#ifndef AAI_POSTS_NORD
        if (nord != prec->nord)
            db_post_events(prec, &prec->nord, DBE_VALUE | DBE_LOG);
#endif
```

2025-07-02 15:06 UTC, anjohnson commented
Core Group: AI on @simon-ess to rebase and add release notes.

2025-07-02 15:10 UTC, simon-ess commented
Rebased, will add release notes shortly.

2025-07-03 07:44 UTC, simon-ess commented
Release note added. @anjohnson

2025-10-23 22:50 UTC, mdavidsaver approved these changes
This still looks ok to me.  With the added release notes, I think this PR is ready to go.

2026-02-04 16:15 UTC, merged