On VxWorks, `stderr` cannot be passed between threads
epics-base/epics-base pull request #417
Opened 2023-08-15 14:29 UTC by dirk-zimoch

On VxWorks, the `stderr` used during initialization may no longer be valid in  `errlogThread`. Thus, do not pass `stderr` directly but initialize `console` to `NULL` instead and later in `errlogThread` use the current `stderr` when `NULL` is found. That means that also the test `isATTY()` can only be done in the `errlogThread` once the current `console` has been decided on.

2023-08-15 14:30 UTC, dirk-zimoch commented
Fixes #416.

2023-08-15 15:46 UTC, mdavidsaver requested changes
I was able to find a... resource on vxworks showing that `stdin`, `stdout`, and `stderr` can evaluate to thread local storage.  These `FILE` reference FDs 0, 1, and 2.  And so are effected by `ioTaskStdSet()`.

So I think this PR is necessary.

However, I think it need to go further to ensure that `errlogSetConsole()` does something sensible with `std*`.

2023-08-15 15:46 UTC, mdavidsaver commented on modules/libcom/src/error/errlog.c
> +    pvt.console = stream;
What happens with `errlogSetConsole(stdout)` or `errlogSetConsole(stderr)`?

I think an explicit test for the three special `std*` is necessary, with the result stored alongside `pvt.console=NULL`.  (passing `stdin` should be an error)

Also, please do not remove `pvt.ttyConsole`.  `isATTY()` is a relatively expensive function, so I think caching the result makes sense.  (or look at speeding up `isATTY()`)

2023-08-15 15:46 UTC, mdavidsaver commented on modules/libcom/src/error/errlog.c
> -    int          ttyConsole;
Again, keep `ttyConsole`.  Also add an enum like:

```c
enum consoleType_t {
    consoleFILE, /* use pvt.console */
    consoleStdout, /* use stdout */
    consoleStderr, /* use stderr */
};
```

2023-08-15 15:46 UTC, mdavidsaver commented on modules/libcom/src/error/errlog.c
> +            int ttyConsole = console ? isATTY(console) : 0;
Rather than evaluating `stderr` and `isATTY(stderr)` every time, do so once on entry to `errlogThread()` as local variables.  The same for `stdout`.

2023-08-15 16:00 UTC, mdavidsaver commented
A note for the future on an approach I am **not** suggesting.  I looked into what it would take to "clone" a `FILE*`.  It appears that MSVC (now?) provides the necessary POSIX functions `fileno()`, `dup()`, `fdopen()`, and `setvbuf()`.  This would improve the safety of `errlogSetConsole()`, but seems like too much effort.

fyi. I do not find a "getter" to match `setvbuf()`.  So I do not think it possible to "clone" the buffer mode.  However, in the context of errlog, forcing `_IOLBF` would be reasonable.

2023-08-16 07:34 UTC, dirk-zimoch commented
My previous idea to use FDs instead of FILE* is blocked by Windows (as usual) not being able to *printf to a FD. GNU/[POSIX.1-2008](http://www.opengroup.org/onlinepubs/9699919799/functions/dprintf.html) has `dprintf` and VxWorks has `fdprintf` for this but I found nothing similar for Windows.

2023-08-16 08:12 UTC, dirk-zimoch commented
Maybe we only need something special for VxWorks. Something like
```console = fileno(stream)<=2 ? fdopen(fileno(stream)) : stream; ```
Of course, also making sure to `if(fileno(console)<=2) fclose(console);` when done.

2023-08-16 08:19 UTC, dirk-zimoch commented
... on the other hand, if `fileno(stream)` returns 2, that really means nothing because the mapping can change. Probably more something like `fdopen(ioTaskStdGet(0,fileno(stream),mode)`. But then cleaning up is more difficult.

2023-08-21 12:01 UTC, dirk-zimoch commented
A less invasive approach: #418

2023-08-24 07:36 UTC, dirk-zimoch commented
Why cloning is necessary: Imagine the calling thread (e.g. the interactive VxWorks shell) calls `errlogSetConsole(NULL)` while having stderr redirected to a file. Simply setting a flag like `consoleStderr` would make the `errlogThread` to use *its own* `stderr` which will *not* use the redirection that was active during `errlogSetConsole()`! This is not what I would expect and it is not what happens on other implementations. Thus, this PR cannot work. Neither with my original approach nor with any other approach that uses any flags and not a clone of the stdout/err `FILE*` in use during `errlogSetConsole()`.
Thus, I close this PR.

2023-08-24 07:36 UTC, closed without merging

2023-08-24 07:47 UTC, mdavidsaver commented
> ... calls `errlogSetConsole(NULL)` while having stderr redirected to a file. ... make the `errlogThread` to use _its own_ `stderr` ...

This is ~what I had in mind.  Although I may be missing some subtlety of vxworks.

To my mind, `errlogSetConsole(NULL)` is expressing something like "log output to default", where "default" is the (global) FD 2.  So I think it is valid that vxWorks pre-thread redirection is not used.  To capture errlog output, it would be necessary to either:

- `dup2()` to replace FD 2  (globally)
- `errlogSetConsole()` with a `FILE*` usable by the errlog thread.

By passing a non-NULL to `errlogSetConsole()`, the caller is taking responsibility for ensuring that the `FILE*` remains valid until `errlogSetConsole()` is called again.