Avoid initMainThread() except on vxworks
epics-base/epics-base pull request #451
Opened 2023-12-22 18:19 UTC by mdavidsaver

Move isOkToBlock tracking to osdThread.  Targets except vxworks can store this flag in epicsThreadOSD. Continue to use TLS w/ vxWorks.  Eliminates one c++ global constructor (cf. #298 and #286).

2024-07-11 19:13 UTC, anjohnson requested changes
Three issues in the VxWorks code with solutions: one build-time, one run-time and one minor optimization.

2024-07-11 19:13 UTC, anjohnson commented on modules/libcom/src/osi/os/vxWorks/osdThread.c
> +        (void)epicsThreadGetIdSelf();
This call to `epicsThreadGetIdSelf()` isn't necessary, the VxWorks implementation just forwards to the OS's `taskIdSelf()` to get the taskId of the shell task that's currently loading `st.cmd`, so it has no side-effects.

2024-07-11 19:13 UTC, anjohnson commented on modules/libcom/src/osi/os/vxWorks/osdThread.c
>          done = 1;
The `epicsThreadSetOkToBlock()` routine can't be called until after `done` has been set; it calls `epicsThreadPrivateCreate()` which calls `epicsThreadInit()` (this routine) which then deadlocks waiting for `lock` to be cleared.

The deadlock doesn't occur if I swap these two lines, which looks safe to do since all VxWorks systems are uni-processor, but I'd appreciate a second pair of eyes on that solution.

2024-07-11 19:13 UTC, anjohnson commented on modules/libcom/src/osi/os/vxWorks/osdThread.c
> +static void epicsThreadOnceIdInit(void *)
```
../osi/os/vxWorks/osdThread.c: In function 'epicsThreadOnceIdInit':
../osi/os/vxWorks/osdThread.c:589: error: parameter name omitted
```

```patch
diff --git a/modules/libcom/src/osi/os/vxWorks/osdThread.c b/modules/libcom/src/osi/os/vxWorks/osdThread.c
index 7a951fee9..b907a7f12 100644
--- a/modules/libcom/src/osi/os/vxWorks/osdThread.c
+++ b/modules/libcom/src/osi/os/vxWorks/osdThread.c
@@ -586,7 +586,7 @@ static epicsThreadPrivateId okToBlockPrivate;
 static const int okToBlockNo = 0;
 static const int okToBlockYes = 1;
 
-static void epicsThreadOnceIdInit(void *)
+static void epicsThreadOnceIdInit(void *not_used)
 {
     okToBlockPrivate = epicsThreadPrivateCreate();
 }
```

2024-09-17 13:23 UTC, mdavidsaver commented on modules/libcom/src/osi/os/vxWorks/osdThread.c
> +        (void)epicsThreadGetIdSelf();
Removed.

2024-09-17 13:25 UTC, mdavidsaver commented on modules/libcom/src/osi/os/vxWorks/osdThread.c
>          done = 1;
Changed as recommended.

> but I'd appreciate a second pair of eyes on that solution.

I think what you say is correct.  By this point, `epicsThreadInit()` is done.

2024-09-17 13:26 UTC, mdavidsaver commented on modules/libcom/src/osi/os/vxWorks/osdThread.c
> +static void epicsThreadOnceIdInit(void *)
parameter name un-omitted.

2024-12-28 01:38 UTC, mdavidsaver commented
I think this is ready for another look.

2025-03-11 21:38 UTC, mdavidsaver commented
Rebased.

2025-03-19 15:53 UTC, merged