replaced the html version of msi document with markdown.
epics-base/epics-base pull request #560
Opened 2024-10-24 13:33 UTC by ttkorhonen

Replaced the html version with Markdown. No changes in content (at least intentional), some formatting and link targets for future use (easier referencing from other documents on readthedocs.) 
As submitted, this PR will remove the html version. The PR can be modified if the html should still be kept.

2024-10-24 14:34 UTC, mdavidsaver approved these changes
I emphatically approve!

2024-10-24 16:03 UTC, anjohnson requested changes
Some small formatting fixes to the Markdown. If you ask GitHub to show this file as a Rich Diff you'll see what it thinks the formatted document should look like. To do that, in the right of the file's header in the "Files changed" tab click the Page icon just left of the "Viewed" check-box.

With those applied this should be good, thanks!

2024-10-24 16:03 UTC, anjohnson commented on modules/database/src/ioc/dbtemplate/msi.md
> +substitutions on macros of the form `\$(var)` and `\${var}`. It uses the
Putting back-slashes `\` inside back-tick quotes like this leaves the back-slashes in the output, which the [HTML version](https://epics.anl.gov/base/R7-0/8-docs/msi.html) doesn't have and would be confusing.

2024-10-24 16:03 UTC, anjohnson commented on modules/database/src/ioc/dbtemplate/msi.md
> +(msitool)=
This `(msitool)=` string doesn't look like normal Markdown syntax to me, does the Sphinx Markdown processor understand it?

2024-10-24 16:03 UTC, anjohnson commented on modules/database/src/ioc/dbtemplate/msi.md
> +`msi -V -g -o _outfile_ -I _dir_ -M _subs_ -S _subfile_ _template_`
Markdown doesn't recognize underscore characters `_` inside back-ticks to generate italics in code-quotes. I would just leave off the underscores around these parameter names.

2024-10-24 16:03 UTC, anjohnson commented on modules/database/src/ioc/dbtemplate/msi.md
> +        $(c) or ${c} is replaced by cval
These 3 lines are being formatted as a code-block literal because of the indent. Making them an indented bulleted list like this should prevent that:

        + `$(a)` or `${a}` is replaced by _aval_
        + `$(b)` or `${b}` is replaced by _bval_
        + `$(c)` or `${c}` is replaced by _cval_

resulting in:

+ `$(a)` or `${a}` is replaced by _aval_
+ `$(b)` or `${b}` is replaced by _bval_
+ `$(c)` or `${c}` is replaced by _cval_

2024-10-24 16:03 UTC, anjohnson commented on modules/database/src/ioc/dbtemplate/msi.md
> +\$(ENV_VAR), which will be expanded before the file is opened.
For display by GitHub either the underscore in `ENV_VAR` needs a back-slash to escape it or those two macros should be inside back-ticks (without escaping the dollar sign).

2024-10-24 21:17 UTC, ttkorhonen commented on modules/database/src/ioc/dbtemplate/msi.md
> +\$(ENV_VAR), which will be expanded before the file is opened.
Readthedocs (sphinx) handles these without escaping the underscore. But I can insert back-ticks.

2024-10-24 21:18 UTC, ttkorhonen commented on modules/database/src/ioc/dbtemplate/msi.md
> +        $(c) or ${c} is replaced by cval
OK.

2024-10-24 21:18 UTC, ttkorhonen commented on modules/database/src/ioc/dbtemplate/msi.md
> +`msi -V -g -o _outfile_ -I _dir_ -M _subs_ -S _subfile_ _template_`
Same as above, back-ticks inserted later.

2024-10-24 21:18 UTC, ttkorhonen commented on modules/database/src/ioc/dbtemplate/msi.md
> +(msitool)=
This is a MyST directive. See https://myst-parser.readthedocs.io/en/latest/syntax/cross-referencing.html#cross-references
This makes cross-referencing easier and more robust.

2024-10-24 21:18 UTC, ttkorhonen commented on modules/database/src/ioc/dbtemplate/msi.md
> +substitutions on macros of the form `\$(var)` and `\${var}`. It uses the
OK, I put the back-ticks in later and missed that effect.

2024-10-24 21:23 UTC, ttkorhonen commented on modules/database/src/ioc/dbtemplate/msi.md
> +`msi -V -g -o _outfile_ -I _dir_ -M _subs_ -S _subfile_ _template_`
Another option would be to leave out the back-ticks and keep the italics. But let us go with the back-ticks.

2024-10-25 14:34 UTC, anjohnson approved these changes

2024-10-30 16:07 UTC, merged