Add debug build configuration for os x mX arch
epics-base/epics-base pull request #569
Opened 2024-11-25 09:13 UTC by simon-ess

Parallel to the darwin-x86 configuration, here is some darwin-aarch64-debug configuration.

2024-11-25 16:46 UTC, anjohnson commented
I suspect we might want to provide a file `CONFIG.darwin-aarch64-debug.darwin-aarch64-debug` too, for building with the right flags when `EPICS_HOST_ARCH` is set to `d-a64-debug` (look at `CONFIG.linux-arm-debug.linux-arm-debug`). That `darwin-x86-debug` doesn't have one probably shows that the `d-x86-debug` target isn't used much (if at all), or that setting `HOST_OPT=NO` doesn't have much effect nowadays.

2024-11-27 15:48 UTC, mdavidsaver commented
Core Group: Looks fine.

2024-12-03 18:04 UTC, anjohnson requested changes
Nit-picking but I think important...

2024-12-03 18:04 UTC, anjohnson commented on configure/os/CONFIG.darwin-x86-debug.Common
> +# CONFIG.darwin-x86-debug.darwin-x86-debug
Please fix the filename:

`s/darwin-x86-debug$/Common/`

2024-12-03 18:04 UTC, anjohnson commented on configure/os/CONFIG.darwin-x86-debug.Common
> +# Definitions for darwin-x86 host - darwin-x86 target build with debug compiler flags
The settings in this file (`CONFIG.darwin-x86-debug.Common`) apply to all builds when the host-arch is `darwin-x86-debug`. The wording of the above comment could be confusing because most cross-targets would *not* be built with debug flags. Please use:

`# Definitions for darwin-x86-debug host builds`

2024-12-03 18:04 UTC, anjohnson commented on configure/os/CONFIG.darwin-aarch64-debug.Common
> +# CONFIG.darwin-aarch64-debug.darwin-aarch64-debug
Please fix the filename:

`s/darwin-aarch64-debug$/Common/`

2024-12-03 18:04 UTC, anjohnson commented on configure/os/CONFIG.darwin-aarch64-debug.Common
> +# Definitions for darwin-aarch64 host - darwin-aarch64 target build with debug compiler flags
The settings in this file (`CONFIG.darwin-aarch64-debug.Common`) apply to all builds when the host-arch is `darwin-aarch64-debug`. The wording of the above comment could be confusing because most cross-targets would _not_ be built with debug flags. Please use:

`# Definitions for darwin-aarch64-debug host builds`

2024-12-11 15:33 UTC, anjohnson approved these changes

2024-12-11 15:33 UTC, merged

2024-12-11 15:33 UTC, anjohnson commented
Core Group: Approved.